#!/usr/bin/env bash

if [ "$1" = "" ]; then
    >&2 echo "usage: derat <file> ..."
    exit 1
fi

mkdir -p dict
touch dict/rats

rats=$(cat dict/rats | grep -v '#' | tr '\n' '|' | awk '{ print(substr($0, 1, length($0) - 1)) }')

if [ -z "$rats" ]; then
    >&2 echo "Error: dict/rats file empty"
    exit 1
fi

pcregrep -M -i -n --color "$rats" "$@"

exit $?
