#!/usr/bin/env bash

set -e

tmpfile=$(mktemp)

name="test-idempotent"
./fix-bib -o $tmpfile "./test-resources/$name.bib"
diff $tmpfile "test-resources/expected/$name.bib"

name="test-names-1"
./fix-bib -n -o $tmpfile "./test-resources/$name.bib"
diff $tmpfile "test-resources/expected/$name.bib"

name="test-lookup-1"
./fix-bib -l -o $tmpfile "./test-resources/$name.bib"
diff $tmpfile "test-resources/expected/$name.bib"

name="test-lookup-2"
./fix-bib -l -o $tmpfile "./test-resources/$name.bib"
diff $tmpfile "test-resources/expected/$name.bib"