#!/usr/bin/env bash

set -e

bin="$1"

if [ "$bin" = "" ]; then
    bin="$HOME/bin"
fi

basepath="https://raw.githubusercontent.com/mlutze/pub-utils/master"

manifest=$(mktemp)

# get the manifest
curl --fail-with-body "$basepath/manifest" > "$manifest"

for file in $(cat "$manifest"); do
    curl "$basepath/$file" > "$bin/$file"
done