name: Tests

on: [pull_request]

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the master branch
        uses: actions/checkout@v2
      - name: Install Bibtex Parser
        run: pip install --no-cache-dir --force-reinstall git+https://github.com/sciunto-org/python-bibtexparser@main
      - name: Install Habanero
        run: pip install habanero
      - name: Run tests
        run: cd test; ./test